{
 "title": "Forensic",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node 0",
   "type": "jdbranham-diagram-panel",
   "description": "The latest three QCs received by node0.",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": {
    "content": "graph LR\n      B1(fa:fa-check  fa:fa-check )--> B2(fa:fa-check  fa:fa-check) --> B3(fa:fa-check  fa:fa-check)\n\n    "
   },
   "targets": [
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B1 AS metric,\n  B1\nFROM node0\nORDER BY round"
    },
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B2 AS metric,\n  B2\nFROM node0\nORDER BY round"
    },
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B3 AS metric,\n  B3\nFROM node0\nORDER BY round"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * from qcs;\n" }
   ]
  },
  {
   "title": "Node 3",
   "type": "jdbranham-diagram-panel",
   "description": "The latest three QCs received by node3.",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": {
    "content": "graph LR\n      B1(fa:fa-check  fa:fa-check )--> B2(fa:fa-check  fa:fa-check) --> B3(fa:fa-check  fa:fa-check)\n\n    "
   },
   "targets": [
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B1\nFROM node3\nORDER BY round"
    },
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B2\nFROM node3\nORDER BY round"
    },
    {
     "rawSql": "SELECT\n  round AS \"time\",\n  B3\nFROM node3\nORDER BY round"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "marcusolsson-dynamictext-panel",
   "description": "Show the recent logs of nodes.",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 8 },
   "options": { "content": "### {{id}} logs\n{{content}}" },
   "targets": [
    {
     "rawSql": "SELECT\n  id, content\nFROM text\nWHERE id in ('node0', 'node1', 'node2', 'node3')"
    }
   ]
  }
 ]
}